import React,{useState} from 'react';

function Example() {
  const [readMore,setReadMore]=useState(false);
  const extraContent=<div>
      <p className="extra-content">
      In World of Warcraft, the Alliance can boast a trio that is equally impressive and varied, Stormwind, Darnassus and Ironforge. Launched in November, Blizzard's massively multiplayer title features eight playable races, the four named above plus Trolls, Night Elves, Dwarves and Gnomes. The game also offers a total of nine classes that range from Warrior, Paladin, Hunter and Rogue to Druid, Priest, Shaman, Mage and Warlock. The world in which they reside has approximately three dozen regions to explore, each with its own environment and inhabitants. Since it launched in the latter half of November, the title has attracted hundreds of thousands of players. It has also won many awards, one being our highest honor, Game of the Year, so it's clearly a critical and commercial success. The key question, of course, is how well it suits your personal preferences.

In this regard, World of Warcraft's primary strength may be its accessibility, which includes various major factors. One is a relatively gentle learning curve that starts off at a level that won't automatically deter individuals who play only a few games per year. After installation, account creation and login, the next step is to make a character. This phase involves only a few decisions - race, class and look - so while you can spend time checking out myriad combinations if you so desire, you can also get through it in only a few seconds, especially if you use the random appearance button. The basic gameplay is also easy to pick up. You begin life in a newbie area, of which there are six; Dwarves share one with Gnomes, as do Orcs and Trolls, while the other races have their own. You can leave immediately if you wish, but it's probably worth completing at least a few of the easy quests that are made available. During this time, you'll learn to use your starter weapon and first special attack or spell, plus the basics of acquiring new ones, talking with NPCs, purchasing and selling items, equipping arms and armor, etc. Quite a few hints and tips are available; you can turn them off if you don't need them. In only a few minutes, you'll level up for the first time, and within an hour or two, you'll advance enough to receive an assignment that takes you out to see the rest of Azeroth.

The world consists of irregularly shaped regions that are relatively small; you can probably run across most of them in five to 10 minutes. The above-noted accessibility aspect comes into play in a couple of ways. One is that there's lots of content, which means you won't go very far without seeing something you can potentially investigate, fight or do. The other is that you're seldom very far from one or more of the game's many paths. You can certainly wander off them easily enough, but the main point here is that they provide a pretty constant sense of direction. This may not seem like much if you're an experienced online world gamer, but if you're not, Blizzard makes sure you always feel like you have somewhere to go. Because of the heavily quest-based gameplay, you always have something to do as well. To help the world feel small and full, players can gain various means of travel that are faster than normal. One is simply running faster. Not every class can do that, but they all have mounts, although you have to reach level 40 before you can buy one. In addition, there are different methods of moving between specific locations. These include flying animals you can rent, underground trams, boats and zeppelins. Each character can also have a hearthstone. You can use this once an hour to return to an inn you've previously designated, and which you can change by visiting your new destination and speaking with the innkeeper.

Another user-friendly characteristic is the viability of solo play. To be clear, advancement is quicker if you group. Depending how well you and your companions mesh, experience can be gained quite a bit more rapidly. However, on those occasions when you can't find suitable companions or simply want to go it alone, you can. Quests are more difficult and time-consuming to complete without company, but except for a fairly small proportion of highly group-oriented ones, they can be done if you use enough patience, care and strategy. And if you just have five or 10 minutes and want to head out and whack some critters, that's feasible as well since you don't have to take the time to find or assemble a party.

As you advance, you'll gain the chance to buy additional spells and/or abilities. A pre-set selection becomes available upon reaching each even-numbered level. In effect, this helps ramp up the learning curve gradually, especially when you consider that some purchases are simply stronger versions rather than entirely new. From level 10, you also receive a talent point each time you move up. These are spent on a tree-like system that lets you add to your repertoire and/or improve certain aspects. For instance, a Mage can only gain certain spells via the talent system, while other possible expenditures increase parameters like range, damage and casting speed. You don't get enough points for everything, so you have to pick and choose, which provides a bit of character differentiation.


Regarding the nature of the nine classes, there isn't much in the way of departures from fairly standard archetypes; a Warrior is an armored close combat specialist, a Mage is a fragile damage dealer, a Paladin is a fighter-healer, etc. The Druid may be the most unusual. In its normal form, it's a sort of nuker-healer hybrid. It can also transform into a melee-oriented bear and a rogue-like cat. Within the nine options, there's a decent overall variety, but once you've made a choice, you can't change classes or multi-class. Races have different base attributes, so a Human Hunter and a Troll one aren't exactly the same. However, they can acquire precisely the same abilities at exactly the same levels, so although you can choose different talents and use items with different bonuses, they still play pretty similarly. This is, of course, pretty much inherent to any class-based system; it's important to pick one that fits your play style.

Visually, the art team has done a commendable job creating a world in which the locations and inhabitants are diverse, but where everything comes together and feels like it belongs. If you're familiar with the franchise, the overall look immediately says Warcraft. It's somewhat cartoon-like, not striving for realism. There's nice lighting plus some cool spell and other effects, but in general, the polygon counts are not overly high. Neither are the hardware requirements. As a result, you won't get the same level of eye candy that you will from the latest shooters, but you can run the game on a lot more machines. It's natural that all this talk about accessibility would raise a question as to the game's depth. In this respect, World of Warcraft is a typical Blizzard endeavor. It's certainly not at the top of the heap, but there's considerably more than you might think at first glance. You don't necessarily see it right away because it's seamlessly integrated. As a prime example, quite a few of the quests don't simply stand alone. Instead, they run in brief series that tell little tales while also incorporating bits of lore. In a similar vein, you will occasionally come upon books, notes and other pieces of writing that add to the fullness of the overall environment. Still, in areas such as character development, the levels of complexity and player flexibility are fairly modest. This may be an issue for some players.

A far larger concern involves server performance and stability. Frankly, the amount of down time is disappointing. For quite some time, every server was scheduled for an hour of maintenance every day. It's now one four-hour maintenance break per week. Despite this, there are still occasional outages. Recently, certain servers have had another performance issue causing waits of an hour or more before being able to log in. To its credit, Blizzard has responded by giving additional days of playing time, but the point is that the underlying problem shouldn't exist in the first place. About a week after launch, I expressed the hope such deficiencies would be fixed before long. Unfortunately, after almost two months of service, there has been no noticeable improvement. It should also be noted that a few quests are bugged and cannot be completed. 
      </p>
  </div>
  const linkName=readMore?'Read Less << ':'Read More >> '
  return (
    <div className="App">
      <a className="read-more-link" onClick={()=>{setReadMore(!readMore)}}><h2>{linkName}</h2></a>
      {readMore && extraContent}
    </div>
  );
}

export default Example;
